@extends('layouts.app')
@section('title', 'Daily Sales Report')

@section('content')
<style>
  .report-wrapper { padding: 25px 30px; }
  .report-card {
    background: #fff; border-radius: 6px; 
    box-shadow: 0 2px 6px rgba(0,0,0,0.05); 
    max-width: 1000px; margin-left: 0;
  }
  .report-card .card-header {
    font-weight: 600; background: #fff; 
    border-bottom: 1px solid #e9ecef; 
    color: #333; padding: 15px 20px;
  }
  .report-card .card-body { padding: 25px 20px; }
  .btn { border-radius: 4px; font-weight: 500; }
  .btn-primary { background-color: #0d6efd; border: none; }
  .btn-primary:hover { background-color: #0b5ed7; }
  .btn-success { background-color: #198754; border: none; }
  .btn-success:hover { background-color: #157347; }
  .form-select { height: 38px; border-radius: 4px; }
  .table { margin-top: 20px; }
  .table thead th { background-color: #1b1f23; color: #fff; text-align: center; }
  .table td { text-align: center; }
  .generated-by {
    margin-top: 15px; font-style: italic; color: #666; 
    font-size: 0.9rem;
  }
</style>

<div class="report-wrapper">
  <div class="report-card card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <span><i class="bi bi-clipboard-data"></i> Daily Sales — {{ \Carbon\Carbon::create()->month($month)->format('F') }} {{ $year }}</span>
      <form method="GET" action="{{ route('reports.daily.download', ['month' => $month, 'year' => $year]) }}">
        <div class="d-flex align-items-center">
          <select name="format" class="form-select me-2" style="width:130px;">
            <option value="csv">CSV</option>
            <option value="pdf">PDF</option>
            <option value="xlsx">Excel</option>
          </select>
          <button type="submit" class="btn btn-success">
            <i class="bi bi-download"></i> Download
          </button>
        </div>
      </form>
    </div>

    <div class="card-body">
      @if($sales->count() > 0)
        <div class="table-responsive">
          <table class="table table-bordered table-hover align-middle">
            <thead>
              <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Quantity Sold</th>
                <th>Total</th>
                <th>Admin</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              @php $grandTotal = 0; @endphp
              @foreach($sales as $index => $sale)
                @php $grandTotal += $sale->total_saleing_price; @endphp
                <tr>
                  <td>{{ $index + 1 }}</td>
                  <td>{{ $sale->product_name }}</td>
                  <td>{{ $sale->qty }}</td>
                  <td>₱{{ number_format($sale->total_saleing_price, 2) }}</td>
                  <td>{{ $sale->admin_name ?? 'N/A' }}</td>
                  <td>{{ \Carbon\Carbon::parse($sale->date)->format('F j, Y') }}</td>
                </tr>
              @endforeach
              <tr>
                <td colspan="3" class="text-end fw-bold">TOTAL</td>
                <td class="fw-bold">₱{{ number_format($grandTotal, 2) }}</td>
                <td colspan="2"></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="generated-by">
          Report generated by: <strong>{{ $generatedBy }}</strong>
        </div>
      @else
        <div class="alert alert-warning text-center mt-3">
          <strong>No daily sales found for this month.</strong>
        </div>
      @endif
    </div>
  </div>
</div>
@endsection
